name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Publish
        run: dotnet publish src/Flow.Launcher.Plugin.Invidious -c Release -r win-x64 --no-self-contained

      - name: Package
        shell: pwsh
        run: |
          Compress-Archive -Path "src/Flow.Launcher.Plugin.Invidious/bin/Release/win-x64/publish/*" -DestinationPath "Flow.Launcher.Plugin.Invidious.zip" -Force

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Flow.Launcher.Plugin.Invidious.zip
